module.exports = [
  'App',
  'Authorized',
  'Cropper',
  'EditableInput',
  'EmailCaptcha',
  'Exception',
  'GlobalFooter',
  'GlobalHeader',
  'HeaderSearch',
  // 'MainMenu',
  'MobileCaptcha',
  'NoticeIcon',
  'PageLoading',
  'Script',
  'SelectLang',
  'SiderMenu',
  'Support',
  'TopNavHeader',
  'ShareAppMessage',
  '_utils',
];
