// !!! This file will be generated by ./tool/create.js auto

import App from '../../scaffold/app/web/src/components/App';
import Authorized from '../../scaffold/app/web/src/components/Authorized';
import Cropper from '../../scaffold/app/web/src/components/Cropper';
import EditableInput from '../../scaffold/app/web/src/components/EditableInput';
import EmailCaptcha from '../../scaffold/app/web/src/components/EmailCaptcha';
import Exception from '../../scaffold/app/web/src/components/Exception';
import GlobalFooter from '../../scaffold/app/web/src/components/GlobalFooter';
import GlobalHeader from '../../scaffold/app/web/src/components/GlobalHeader';
import HeaderSearch from '../../scaffold/app/web/src/components/HeaderSearch';
import MobileCaptcha from '../../scaffold/app/web/src/components/MobileCaptcha';
import NoticeIcon from '../../scaffold/app/web/src/components/NoticeIcon';
import PageLoading from '../../scaffold/app/web/src/components/PageLoading';
import Script from '../../scaffold/app/web/src/components/Script';
import SelectLang from '../../scaffold/app/web/src/components/SelectLang';
import SiderMenu from '../../scaffold/app/web/src/components/SiderMenu';
import Support from '../../scaffold/app/web/src/components/Support';
import TopNavHeader from '../../scaffold/app/web/src/components/TopNavHeader';
import ShareAppMessage from '../../scaffold/app/web/src/components/ShareAppMessage';

export default {
  App,
  Authorized,
  Cropper,
  EditableInput,
  EmailCaptcha,
  Exception,
  GlobalFooter,
  GlobalHeader,
  HeaderSearch,
  MobileCaptcha,
  NoticeIcon,
  PageLoading,
  Script,
  SelectLang,
  SiderMenu,
  Support,
  TopNavHeader,
  ShareAppMessage,
};
