// !!! This file will be generated by ./tool/create.js auto

import App from '../../scaffold/src/components/App';
import Authorized from '../../scaffold/src/components/Authorized';
import BaseForm from '../../scaffold/src/components/BaseForm';
import Cropper from '../../scaffold/src/components/Cropper';
import EditableInput from '../../scaffold/src/components/EditableInput';
import EmailCaptcha from '../../scaffold/src/components/EmailCaptcha';
import Exception from '../../scaffold/src/components/Exception';
import FormModal from '../../scaffold/src/components/FormModal';
import GlobalFooter from '../../scaffold/src/components/GlobalFooter';
import GlobalHeader from '../../scaffold/src/components/GlobalHeader';
import HeaderSearch from '../../scaffold/src/components/HeaderSearch';
import HeaderDropdown from '../../scaffold/src/components/HeaderDropdown';
import LayoutBase from '../../scaffold/src/components/LayoutBase';
import LayoutFooter from '../../scaffold/src/components/LayoutFooter';
import LayoutHeader from '../../scaffold/src/components/LayoutHeader';
import MobileCaptcha from '../../scaffold/src/components/MobileCaptcha';
import NoticeIcon from '../../scaffold/src/components/NoticeIcon';
import PageLoading from '../../scaffold/src/components/PageLoading';
import Script from '../../scaffold/src/components/Script';
import SelectHiddenOptions from '../../scaffold/src/components/SelectHiddenOptions';
import SelectLang from '../../scaffold/src/components/SelectLang';
import ShareAppMessage from '../../scaffold/src/components/ShareAppMessage';
import SiderMenu from '../../scaffold/src/components/SiderMenu';
import Support from '../../scaffold/src/components/Support';
import TopNavHeader from '../../scaffold/src/components/TopNavHeader';

export default {
  App,
  Authorized,
  BaseForm,
  Cropper,
  EditableInput,
  EmailCaptcha,
  Exception,
  FormModal,
  GlobalFooter,
  GlobalHeader,
  HeaderSearch,
  HeaderDropdown,
  LayoutBase,
  LayoutFooter,
  LayoutHeader,
  MobileCaptcha,
  NoticeIcon,
  PageLoading,
  Script,
  SelectHiddenOptions,
  SelectLang,
  ShareAppMessage,
  SiderMenu,
  Support,
  TopNavHeader,
};
